- name: Install k3s master
  become: true
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --flannel-iface ens3" sh -
  args:
    creates: /etc/rancher/k3s/k3s.yaml

- name: Get join token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  changed_when: false

- name: Save join token for workers
  copy:
    content: "{{ k3s_token.stdout }}"
    dest: /tmp/k3s_token
    mode: '0600'