- name: Deploy Node.js app
  hosts: all
  become: yes
  vars:
    node_version: "18.x"
    app_dir: /var/www/nodeapp
  tasks:
    - name: Install curl
      apt: { name: curl, state: present, update_cache: yes }

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy app files
      copy:
        src: ./app/
        dest: "{{ app_dir }}"
        owner: ubuntu
        group: ubuntu

    - name: Install app dependencies
      npm:
        path: "{{ app_dir }}"
        production: yes

    - name: Start the app with pm2
      command: pm2 start "{{ app_dir }}/server.js" --name "nodeapp"
      args:
        chdir: "{{ app_dir }}"
      become: false
