- name: Fetch token from master
  slurp:
    src: /tmp/k3s_token
  delegate_to: "{{ groups['k3s_master'][0] }}"
  register: token_slurp

- name: Decode token
  set_fact:
    k3s_token: "{{ token_slurp.content | b64decode }}"

- name: Get master IP address
  set_fact:
    master_ip: "{{ hostvars[groups['k3s_master'][0]].ansible_host | default(groups['k3s_master'][0]) }}"

- name: Check connectivity to k3s master API port
  wait_for:
    host: "{{ master_ip }}"
    port: 6443
    timeout: 10

- name: Detect worker's main network interface
  command: ip route get 8.8.8.8
  register: ip_route
  changed_when: false

- set_fact:
    flannel_iface: "{{ ip_route.stdout.split('dev')[1].split()[0] }}"

- name: Install k3s agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ k3s_token }} INSTALL_K3S_EXEC="--flannel-iface {{ flannel_iface }}" sh -
  args:
    creates: /etc/systemd/system/k3s-agent.service